name: Continuous Integration

on:
  pull_request:
    branches:
    - main

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/test

jobs:
  build_scan_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build image
      run: |
        docker build -t "$IMAGE_NAME:pr-${{ steps.branch-name.outputs.current_branch }}" .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: $IMAGE_NAME:pr-${{ steps.branch-name.outputs.current_branch }}
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Log in to Docker Hub
      if: success()
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push image to registry
      if: success()
      run: |
        docker push $IMAGE_NAME:pr-${{ steps.branch-name.outputs.current_branch }}

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.5.0

    - name: Deploy to k8s
      run: |
        sed -i "s|image: YOUR_DOCKER_REGISTRY/test:latest|image: $IMAGE_NAME:pr-${{ steps.branch-name.outputs.current_branch }}|g" k8s/app.yml
        kubectl apply -f k8s/

    - name: Test API endpoint
      run: |
        sleep 60
        kubectl port-forward svc/nest-app 3000:3000 &
        sleep 5
        response=$(curl -s http://localhost:3000/redis)
        if [ "$response" != '{"status":true}' ]; then
          echo "API test failed. Unexpected response: $response"
          exit 1
        else
          echo "API test passed."
        fi
