name: Continuous Integration

on:
  pull_request:
    branches:
    - main

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/test

jobs:
  build_scan_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build image
      run: |
        docker build -t "${{ env.IMAGE_NAME }}:pr-${{ steps.branch-name.outputs.current_branch }}" .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.IMAGE_NAME }}:pr-${{ steps.branch-name.outputs.current_branch }}
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Log in to Docker Hub
      if: success()
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push image to registry
      if: success()
      run: |
        docker push ${{ env.IMAGE_NAME }}:pr-${{ steps.branch-name.outputs.current_branch }}

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.5.0

    - name: Deploy to k8s
      run: |
        sed -i "s|image: YOUR_DOCKER_REGISTRY/test:latest|image: ${{ env.IMAGE_NAME }}:pr-${{ steps.branch-name.outputs.current_branch }}|g" k8s/app.yml
        kubectl apply -f k8s/

    - name: Test API endpoint
      run: |
        echo "Waiting for Ingress to be ready..."
        sleep 60
        INGRESS_IP=$(kubectl get ingress nestjs-app-ingress -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        if [ -z "$INGRESS_IP" ]; then
          echo "Failed to get Ingress IP. Trying Node IP..."
          INGRESS_IP=$(kubectl get node -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')
        fi
        
        if [ -z "$INGRESS_IP" ]; then
          echo "Failed to get any IP."
          exit 1
        fi

        echo "Testing Ingress at IP: $INGRESS_IP"
        response=$(curl -s http://$INGRESS_IP/redis)
        if [ "$response" != '{"status":true}' ]; then
          echo "API test failed. Unexpected response: $response"
          exit 1
        else
          echo "API test passed."
        fi
