name: CI/CD Pipeline

on:
  push:
    branches:
    - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/test:latest

  deploy:
    needs: build_and_push
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update and Deploy to Kubernetes
      run: |
        sed -i "s|image: YOUR_DOCKER_REGISTRY/test:latest|image: ${{ secrets.DOCKER_USERNAME }}/test:latest|g" k8s/app.yml
        sed -i "s/REDIS_PASSWORD: \"\"/REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}/g" k8s/secret.yml
        kubectl apply -f k8s/
